#!/usr/bin/env bash
# Hermetic provider fixtures for the v10 orchestrator failure-injection suite.

v10_fixture_install() {
    local root="$1" scenario="$2"
    local bin="$root/bin" ledger="$root/provider-calls.tsv" child_pid="$root/child.pid"
    mkdir -p "$bin"

    # Paths and scenario names are generated by mktemp/test-framework and contain
    # no shell metacharacters. Embed them so provider env -i isolation cannot
    # accidentally re-import test controls or host credentials.
    sed \
      -e "s|@SCENARIO@|$scenario|g" \
      -e "s|@LEDGER@|$ledger|g" \
      -e "s|@CHILD_PID@|$child_pid|g" \
      "$V10_FIXTURE_TEMPLATE" > "$bin/v10-provider"
    chmod 755 "$bin/v10-provider"

    local name
    for name in agy qwen claude codex command-code opencode copilot agent grok vibe ollama; do
        ln -s "v10-provider" "$bin/$name"
    done

    printf '%s\n' "$bin"
}

v10_fixture_write_template() {
    local destination="$1"
    V10_FIXTURE_TEMPLATE="$destination"
    export V10_FIXTURE_TEMPLATE
    cat > "$destination" <<'FIXTURE'
#!/usr/bin/env bash
set -u

scenario='@SCENARIO@'
ledger='@LEDGER@'
child_pid_file='@CHILD_PID@'
provider="$(basename "$0")"

case " $* " in
    *" --version "*|*" version "*)
        printf 'control\t%s\tversion\n' "$provider" >> "$ledger"
        case "$provider" in
            claude) printf '%s\n' '2.1.219 (Claude Code)' ;;
            codex) printf '%s\n' 'codex-cli 0.144.0' ;;
            agy) printf '%s\n' 'agy 1.0.0' ;;
            *) printf '%s\n' "$provider fixture 1.0.0" ;;
        esac
        exit 0
        ;;
    *" --help "*|*" help "*|*" auth status "*|*" status --json "*)
        printf 'control\t%s\tstatus\n' "$provider" >> "$ledger"
        printf '%s\n' '--print --sandbox --dangerously-skip-permissions --print-timeout --model'
        exit 0
        ;;
esac

if [[ "$provider" != agy ]]; then
    printf 'unexpected\t%s\t%s\n' "$provider" "$*" >> "$ledger"
    exit 97
fi

attempt=1
if [[ -f "$ledger" ]]; then
    attempt=$(awk -F '\t' '$1 == "dispatch" && $2 == "agy" {n++} END {print n + 1}' "$ledger")
fi
printf 'dispatch\tagy\t%s\t%s\n' "$attempt" "$scenario" >> "$ledger"

case "$scenario" in
    success)
        printf '%s\n' 'Substantive end-to-end provider result.'
        ;;
    auth-fail)
        printf '%s\n' 'authentication failed: injected credential rejection' >&2
        exit 1
        ;;
    exit-zero-empty)
        :
        ;;
    exit-zero-whitespace)
        printf ' \n\t\n'
        ;;
    exit-zero-placeholder)
        printf '%s\n' 'Provider available'
        ;;
    timeout)
        sleep 30
        ;;
    partial-then-timeout)
        printf '%s\n' 'partial output that must not contribute'
        sleep 30
        ;;
    child-tree)
        (trap 'exit 0' TERM INT; sleep 30) &
        child=$!
        printf '%s\n' "$child" > "$child_pid_file"
        wait "$child"
        ;;
    refusal)
        printf '%s\n' "I can't assist with that request" >&2
        exit 1
        ;;
    sigsegv-then-success)
        if [[ "$attempt" -eq 1 ]]; then
            printf '%s\n' 'synthetic SIGSEGV from fixture' >&2
            kill -SEGV "$$"
        fi
        printf '%s\n' 'Recovered substantive provider result.'
        ;;
    output-then-stdin-close)
        if IFS= read -r ignored; then
            printf '%s\n' 'fixture unexpectedly received provider stdin' >&2
            exit 98
        fi
        printf '%s\n' 'Substantive result survived normal closed stdin.'
        printf '%s\n' 'write_stdin failed: stdin is closed for this session' >&2
        ;;
    oversize)
        printf '%s\n' 'oversize fixture should be rejected before provider invocation' >&2
        exit 99
        ;;
    persistence-fail|health-fail)
        printf '%s\n' "$scenario fixture should not be dispatched" >&2
        exit 99
        ;;
    *)
        printf '%s\n' "unknown fixture scenario: $scenario" >&2
        exit 2
        ;;
esac
FIXTURE
}
